/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Currency_Convertor;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class MyCurrencyConvertor extends javax.swing.JFrame {

String[] currencyUnits =
{
    "Units",
    /*
    "Indian Rupee",
    "Kuwaiti Dinar",
    "Bahraini Dinar",
    "Qmani Rial",
    "Jordanian Dinar",
    "British Pound",
    "Gibraitar Pound",
    "Cayman Island Dollar",
    "Swiss Franc",
    "Euro",
    "United States Dollar",
    "Pakistani Rupee",
    "Iraqi Dinar",
    "Ugandan Shilling",
    "Paraguayan Guarani",
    "Guinean Franc",
    "Uzbekistani Som",
    "Indonesian Rupiah",
    "Lao/Laotian Kip",
    "Vietnamese Dong",
    "Iranian Rial",          */
    
    "INR",
    "KWD",
    "BHD",
    "OMR",
    "JOD",
    "GBP",
    "GIP",
    "KYD",
    "CHF",
    "EUR",
    "USD",
    "PKR",
    "IQD",
    "USH",
    "PYG",
    "GNF",
    "UZS",
    "IDR",
    "LAK",
    "VND",
    "IRR",
};


double INR = 103.77;
double KWD = 0.38;
double BHD = 0.47;
double OMR = 0.48;
double JOD = 0.88;
double GBP = 1.00;
double GIP = 0.99;
double KYD = 1.03;
double CHF = 1.08;
double EUR = 1.16;
double USD = 1.24;
double PKR = 383.95;
double IQD = 1631.95;
double USH = 4651.84;
double PYG = 9062.42;
double GNF = 10706.90;
double UZS = 15139.90;
double IDR = 19117.20;
double LAK = 24682.80;
double VND = 30032.10;
double IRR = 52664.51;


    /**
     * Creates new form MyCurrencyConvertor
     */
    public MyCurrencyConvertor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SecondCountry = new javax.swing.JComboBox<>();
        FirstCountry = new javax.swing.JComboBox<>();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FirstCurrencyUnit = new javax.swing.JLabel();
        SecondCurrencyUnit = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabel1.setText("Currency Convertor");

        SecondCountry.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        SecondCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "India", "Kuwait", "Bahrain", "Oman", "Jordan", "United Kingdom", "Gibraltar", "Cayman Islands", "Switzerland", "Germany", "USA", "Pakistan", "Iraq", "Uganda", "Paraguay", "Guinea", "Uzbekistan", "Indonesia", "Laos", "Vietnam", "Iran" }));
        SecondCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SecondCountryItemStateChanged(evt);
            }
        });

        FirstCountry.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        FirstCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "India", "Kuwait", "Bahrain", "Oman", "Jordan", "United Kingdom", "Gibraltar", "Cayman Islands", "Switzerland", "Germany", "USA", "Pakistan", "Iraq", "Uganda", "Paraguay", "Guinea", "Uzbekistan", "Indonesia", "Laos", "Vietnam", "Iran" }));
        FirstCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FirstCountryItemStateChanged(evt);
            }
        });
        FirstCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstCountryActionPerformed(evt);
            }
        });

        t2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        t1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel2.setText("From Currency");

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel3.setText("To Currency");

        FirstCurrencyUnit.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        FirstCurrencyUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FirstCurrencyUnit.setText("Units");

        SecondCurrencyUnit.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        SecondCurrencyUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SecondCurrencyUnit.setText("Units");

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jButton2.setText("Convert Currency");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(FirstCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(SecondCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(FirstCurrencyUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(SecondCurrencyUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(130, 130, 130))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton2)
                        .addGap(54, 54, 54)
                        .addComponent(jButton1)
                        .addGap(77, 77, 77)
                        .addComponent(jButton3)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecondCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstCurrencyUnit)
                    .addComponent(SecondCurrencyUnit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // convert currency
        
        if(FirstCountry.getSelectedIndex()==0||SecondCountry.getSelectedIndex()==0||t1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Select Country and must input the amount","Error Message",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        double amountToChange = Double.parseDouble(t1.getText());
        double amountInPounds = 0.0;
        
        switch(FirstCountry.getSelectedItem().toString())
        {
            case "India": amountInPounds = amountToChange / INR;break;
            case "Kuwait": amountInPounds = amountToChange / KWD;break;
            case "Bahrain": amountInPounds = amountToChange / BHD;break;
            case "Oman": amountInPounds = amountToChange / OMR;break;
            case "Jordan": amountInPounds = amountToChange / JOD;break;
            case "United Kingdom": amountInPounds = amountToChange / GBP;break;
            case "Gibraltar": amountInPounds = amountToChange / GIP;break;
            case "Cayman Islands": amountInPounds = amountToChange / KYD;break;
            case "Switzerland": amountInPounds = amountToChange / CHF;break;
            case "Germany": amountInPounds = amountToChange / EUR;break;
            case "USA": amountInPounds = amountToChange / USD;break;
            case "Pakistan": amountInPounds = amountToChange / PKR;break;
            case "Iraq": amountInPounds = amountToChange / IQD;break;
            case "Uganda": amountInPounds = amountToChange / USH;break;
            case "Paraguay": amountInPounds = amountToChange / PYG;break;
            case "Guinea": amountInPounds = amountToChange / GNF;break;
            case "Uzbekistan": amountInPounds = amountToChange / UZS;break;
            case "Indonesia": amountInPounds = amountToChange / IDR;break;
            case "Laos": amountInPounds = amountToChange / LAK;break;
            case "Vietnam": amountInPounds = amountToChange / VND;break;
            case "Iran": amountInPounds = amountToChange / IRR;
            default : amountInPounds = 0.0;
        }
        double amountChanged = 0.0;
        switch(SecondCountry.getSelectedItem().toString())
        {
            case "India": amountChanged = amountInPounds * INR;break;
            case "Kuwait": amountChanged = amountInPounds * KWD;break;
            case "Bahrain": amountChanged = amountInPounds * BHD;break;
            case "Oman": amountChanged = amountInPounds * OMR;break;
            case "Jordan": amountChanged = amountInPounds * JOD;break;
            case "United Kingdom": amountChanged = amountInPounds * GBP;break;
            case "Gibraltar": amountChanged = amountInPounds * GIP;break;
            case "Cayman Islands": amountChanged = amountInPounds * KYD;break;
            case "Switzerland": amountChanged = amountInPounds * CHF;break;
            case "Germany": amountChanged = amountInPounds * EUR;break;
            case "USA": amountChanged = amountInPounds * USD;break;
            case "Pakistan": amountChanged = amountInPounds * PKR;break;
            case "Iraq": amountChanged = amountInPounds * IQD;break;
            case "Uganda": amountChanged = amountInPounds * USH;break;
            case "Paraguay": amountChanged = amountInPounds * PYG;break;
            case "Guinea": amountChanged = amountInPounds * GNF;break;
            case "Uzbekistan": amountChanged = amountInPounds * UZS;break;
            case "Indonesia": amountChanged = amountInPounds * IDR;break;
            case "Laos": amountChanged = amountInPounds * LAK;break;
            case "Vietnam": amountChanged = amountInPounds * VND;break;
            case "Iran": amountChanged = amountInPounds * IRR;
            default : amountChanged = amountInPounds * 0.0;
        }
        
        String value = String.format("%.2f",amountChanged);
        t2.setText(value);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void FirstCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FirstCountryItemStateChanged
        int position = FirstCountry.getSelectedIndex();
        
        FirstCurrencyUnit.setText(currencyUnits[position]);
    }//GEN-LAST:event_FirstCountryItemStateChanged

    private void SecondCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SecondCountryItemStateChanged
       int position = SecondCountry.getSelectedIndex();
        
        SecondCurrencyUnit.setText(currencyUnits[position]);
    }//GEN-LAST:event_SecondCountryItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FirstCountry.setSelectedIndex(0);
        SecondCountry.setSelectedIndex(0);
        t1.setText(null);
        t2.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FirstCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstCountryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCurrencyConvertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCurrencyConvertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCurrencyConvertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCurrencyConvertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCurrencyConvertor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FirstCountry;
    private javax.swing.JLabel FirstCurrencyUnit;
    private javax.swing.JComboBox<String> SecondCountry;
    private javax.swing.JLabel SecondCurrencyUnit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
